spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example  
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

server:
  port: 9090
  servlet:
    context-parameters:
      javax.servlet.jsp.jstl.fmt.localizationContext: resources
      javax.servlet.jsp.jstl.fmt.locale: ru



